add_subdirectory(siren_app)
add_subdirectory(siren_asset)
add_subdirectory(siren_common)
add_subdirectory(siren_ecs)
add_subdirectory(siren_input)
add_subdirectory(siren_io)
add_subdirectory(siren_log)
add_subdirectory(siren_math)
add_subdirectory(siren_reflect)
add_subdirectory(siren_render)
add_subdirectory(siren_sync)
add_subdirectory(siren_time)
add_subdirectory(siren_window)
