module;

#include <memory>
#include <vector>
#include "assert.hpp"

export module siren.asset.asset_pool;

import siren.log;
import siren.asset.asset;
import siren.asset.asset_id;

namespace siren::asset {

/** @brief Base AssetPool class used for polymorphism. */
export class AssetPoolBase {
public:
    virtual ~AssetPoolBase() = 0;
};

/**
 * @brief The means of asset storage in siren. Manages
 * asset lifetime as well as providing AssetID's and AssetHandle's.
 * @tparam A The asset type this pool stores.
 */
export template <IsAsset A>
class AssetPool final : public AssetPoolBase {
public:
    using GenerationType = AssetID::GenerationType;
    using IndexType      = AssetID::IndexType;
    using TypeID         = AssetID::TypeID;
    using RefCount       = u32;

    ~AssetPool() override = default;

private:
    friend class AssetServer;
    friend class LoadContext;

    /// @brief A storage element in the AssetPool.
    struct PoolEntry {
        std::unique_ptr<A> asset  = nullptr; ///< @brief The stored asset.
        GenerationType generation = 0;       ///< @brief The generation of this storage slot. Useful for reusing slots.
        RefCount ref_count        = 0;       ///< @brief The number of handles referencing this asset.

        // @formatter:off
        void kill() { asset.reset(nullptr); generation++; ref_count = 0; }
        // @formatter:on
    };

    /// @brief The AssetPool's data.
    struct AssetPoolData {
        std::vector<PoolEntry> storage;   ///< @brief Dense asset storage.
        std::vector<IndexType> free_list; ///< @brief Indices that have been freed and should be used.
    };

public:
    /// @brief Creates a new AssetID for this pool, as well as allocates it a storage slot.
    [[nodiscard]]
    auto reserve() -> AssetID {
        IndexType idx;

        if (!m_data.free_list.empty()) {
            idx = m_data.free_list.back();
            m_data.free_list.pop_back();
        } else {
            idx = static_cast<IndexType>(m_data.storage.size());
            m_data.storage.emplace_back(); // grow storage so we don't mess array indexing up
        }

        auto& pool_entry     = m_data.storage[idx];
        pool_entry.asset     = nullptr;
        pool_entry.ref_count = 0;

        return AssetID{ idx, pool_entry.generation, AssetID::get_type_id<A>() };
    }

    /// @brief Adds an asset and takes ownership.
    [[nodiscard]]
    auto add(std::unique_ptr<A>&& asset) -> AssetID {
        const AssetID id = reserve();
        PoolEntry& entry = m_data.storage[id.index()];
        entry.asset      = std::move(asset);
        return id;
    }

    /// @brief Stores an asset into this pool and associates it with the given AssetID.
    /// The ID should be generated by this pool.
    auto link(const AssetID id, std::unique_ptr<A>&& asset) -> void {
        SIREN_ASSERT(is_valid_id(id), "Invalid AssetID passed: {}", id);
        PoolEntry& entry = m_data.storage[id.index()];
        entry.asset      = std::move(asset);
    }

    /// @brief Returns the asset associated with the given ID, or nullptr.
    [[nodiscard]]
    auto fetch(const AssetID id) const -> A* {
        if (!is_valid_id(id)) { return nullptr; }
        const PoolEntry& entry = m_data.storage[id.index()];
        return entry.asset.get();
    }

private:
    template <typename>
    friend class StrongHandle;

    auto is_valid_id(const AssetID id) const -> bool {
        if (id.index() >= m_data.storage.size() || !id.is_valid()) { return false; }
        const auto& entry = m_data.storage[id.index()];
        return entry.generation == id.generation();
    }

    auto inc_ref(const AssetID id) -> void {
        if (!is_valid_id(id)) { return; }
        PoolEntry& entry = m_data.storage[id.index()];
        entry.ref_count += 1;
    }

    auto dec_ref(const AssetID id) -> void {
        if (!is_valid_id(id)) { return; }

        PoolEntry& entry = m_data.storage[id.index()];
        if (entry.generation != id.generation()) { return; }

        // todo: we should maybe emit an AssetCleanupEvent? need to handle destruction here an in asset server eventually
        entry.ref_count -= 1;
        if (entry.ref_count == 0) {
            m_data.free_list.emplace_back(id.index());
            entry.kill();
        }
    }

    AssetPoolData m_data;
};
} // namespace siren::asset
