@startuml
'https://plantuml.com/class-diagram

class Scene {

}

class ScriptManager {

}

class NativeScript {
    - HashMap<NativeScriptHandle, NativeScript> m_scripts{};
}

ScriptManager *-- NativeScript

@enduml